calibration_environment <- function(baseline_calibration = FALSE,
                                    configuration = config){
  
  run_dynamo(config_list = configuration)
  
  list2env(configuration,envir = environment())
  list2env(input,envir = environment())
  
  # Calibration of baseline and scenario shocks script : objective is to create the calibration databases for the baseline and for each shock. 
  
  ## A. Loading calib.csv generated by dynamo 
  
  calib <- fread("src/compiler/calib.csv", data.table = FALSE) %>% 
    select(-all_of("baseyear")) %>% 
    mutate(year = year + input$baseyear) 
  
  OGcalib <- calib
  return_list <- list(
                      OGcalib = OGcalib,
                      baseyear = baseyear,
                      lastyear = lastyear,
                      shockyear = shockyear,
                      max_lags = max_lags,
                      firstyear = firstyear,
                      classification = classification)
  ## B Baseline shock calibration (ie deviating from the steady state at the baseline configuration)
  if(baseline_calibration == FALSE){
    source(calib_baseline,local = TRUE)
    write.csv(baseline_ch, 
              file = file.path("configuration","scenarii_calib","calib_baseline.csv"),
              row.names = FALSE)
    
    ## C Modified calib to integrate potential baseline changes
    
    baseline_vars <- setdiff(names(baseline_ch), "year")
    
    calib_new_base <- OGcalib %>% 
      filter(year %in% c(firstyear:lastyear)) %>% 
      select(-all_of(baseline_vars)) %>% 
      full_join(baseline_ch, by= "year")
    ### calib_new_base now integrates changes with the baseline scenario and should be used to configure shock scenarii
    return_list <- list(calib_new_base = calib_new_base,
                        OGcalib = OGcalib,
                        baseyear = baseyear,
                        lastyear = lastyear,
                        shockyear = shockyear,
                        max_lags = max_lags,
                        firstyear = firstyear,
                        classification = classification)
  }
   return_list
  
}

# plop <- calibration_environment()
