---
title: "Presentation des résultats des simulations"
author: "You"
format: 
  # pres-revealjs:
  #   self-contained: true
  typst: default
params:
    project: "Demo"
    shock_year: 2015
---


```{r}
library(tidyverse)
library(ermeeth)

project_name <- params$project

data_full <- readRDS(file.path("data","output",str_c(project_name,".rds")))

scenarios <- setdiff(unique(data_full$scenario), "baseline")

text <- paste0("\n", scenarios, "\n")
shock_year <- params$shock_year

```


# La présentation

## Scénarios

Nous avons fait tourner le scénario `r text` sur l'année `r shock_year`.

## Résultats

Cela donne le résultat suivant sur le PIB :

```{r}
#| echo: false
#| include: true

data_full_new <- data_full |> 
                 group_by(scenario, variable) |> 
                 arrange(year) |> 

  # Define transformation 
  mutate(dif         = values - values_ref ,   
         rel_dif     = values/values_ref  - 1 ,
         growth_rate = values/lag(values) -  1,
         growth_rate_percent = (values/lag(values) -  1)*100

                  ) |> 
 
                 ungroup() |> as.data.frame()

plot_Y <- data_full_new |>  
  filter(variable %in% c("Y")) |> 
  mutate(index_scen = str_c("c",index_scen)) |> 
  
  ggplot(aes (x = year, y = growth_rate_percent)) +
  geom_line(aes(linetype = index_scen, alpha = scenario))+
  scale_linetype_manual(values = c(c1 = "dashed", c0 ="solid") )

plot_Y
```

